sonar.organization=cyliatabti6-gif
sonar.projectKey=cyliatabti6-gif_tp2-sonarcloud-java
sonar.projectName=tp2-sonarcloud-java

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.java.binaries=build/classes
